<?php
/**
 * ACF Fields Configuration
 * Registers all custom fields via PHP
 */

if (!defined('ABSPATH')) {
    exit;
}

add_action('acf/init', 're_acf_init_fields');

function re_acf_init_fields() {
    // Check if ACF is active
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    $customPostKey = RE_CUSTOM_POST_KEY;

    acf_add_local_field_group(array(
        'key' => 'group_' . $customPostKey . '_fields',
        'title' => __('Real Estate Listing Details', 'real-estate-texas'),
        'fields' => array(
            array(
                'key' => 'field_fbd_description',
                'label' => __('Description', 'real-estate-texas'),
                'name' => 'description',
                'type' => 'textarea',
                'instructions' => __('Detailed description of the property or business', 'real-estate-texas'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_fbd_category',
                'label' => __('Category', 'real-estate-texas'),
                'name' => 'category',
                'type' => 'text',
                'instructions' => __('Business category', 'real-estate-texas'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_fbd_feature_id',
                'label' => __('Feature ID', 'real-estate-texas'),
                'name' => 'feature_id',
                'type' => 'text',
                'instructions' => __('Unique feature identifier', 'real-estate-texas'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_fbd_address',
                'label' => __('Full Address', 'real-estate-texas'),
                'name' => 'address',
                'type' => 'text',
                'instructions' => __('Complete address', 'real-estate-texas'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_fbd_address_info_borough',
                'label' => __('Borough', 'real-estate-texas'),
                'name' => 'address_info_borough',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_address_info_address',
                'label' => __('Street Address', 'real-estate-texas'),
                'name' => 'address_info_address',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_address_info_city',
                'label' => __('City', 'real-estate-texas'),
                'name' => 'address_info_city',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_address_info_zip',
                'label' => __('ZIP Code', 'real-estate-texas'),
                'name' => 'address_info_zip',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_address_info_region',
                'label' => __('Region/State', 'real-estate-texas'),
                'name' => 'address_info_region',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_address_info_country_code',
                'label' => __('Country Code', 'real-estate-texas'),
                'name' => 'address_info_country_code',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_place_id',
                'label' => __('Place ID', 'real-estate-texas'),
                'name' => 'place_id',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_phone',
                'label' => __('Phone', 'real-estate-texas'),
                'name' => 'phone',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_url',
                'label' => __('Website URL', 'real-estate-texas'),
                'name' => 'url',
                'type' => 'url',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_logo',
                'label' => __('Logo URL', 'real-estate-texas'),
                'name' => 'logo',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_main_image',
                'label' => __('Main Image URL', 'real-estate-texas'),
                'name' => 'main_image',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_latitude',
                'label' => __('Latitude', 'real-estate-texas'),
                'name' => 'latitude',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_longitude',
                'label' => __('Longitude', 'real-estate-texas'),
                'name' => 'longitude',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_attributes',
                'label' => __('Attributes', 'real-estate-texas'),
                'name' => 'attributes',
                'type' => 'textarea',
                'instructions' => __('JSON data for available/unavailable attributes', 'real-estate-texas'),
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_fbd_place_topics',
                'label' => __('Place Topics', 'real-estate-texas'),
                'name' => 'place_topics',
                'type' => 'textarea',
                'instructions' => __('JSON data for review topics', 'real-estate-texas'),
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_fbd_rating',
                'label' => __('Rating', 'real-estate-texas'),
                'name' => 'rating',
                'type' => 'textarea',
                'instructions' => __('JSON data for rating information', 'real-estate-texas'),
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_fbd_hotel_rating',
                'label' => __('Hotel Rating', 'real-estate-texas'),
                'name' => 'hotel_rating',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_price_level',
                'label' => __('Price Level', 'real-estate-texas'),
                'name' => 'price_level',
                'type' => 'text',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_people_also_search',
                'label' => __('People Also Search', 'real-estate-texas'),
                'name' => 'people_also_search',
                'type' => 'textarea',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_fbd_work_time',
                'label' => __('Work Time', 'real-estate-texas'),
                'name' => 'work_time',
                'type' => 'textarea',
                'instructions' => __('JSON data for business hours', 'real-estate-texas'),
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 6,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_fbd_popular_times',
                'label' => __('Popular Times', 'real-estate-texas'),
                'name' => 'popular_times',
                'type' => 'textarea',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_fbd_contact_info',
                'label' => __('Contact Info', 'real-estate-texas'),
                'name' => 'contact_info',
                'type' => 'textarea',
                'instructions' => __('JSON data for contact information', 'real-estate-texas'),
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 6,
                'new_lines' => '',
            ),
            array(
                'key' => 'field_fbd_check_url',
                'label' => __('Check URL', 'real-estate-texas'),
                'name' => 'check_url',
                'type' => 'url',
                'instructions' => __('Google Maps or verification URL', 'real-estate-texas'),
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_review_summary_comments',
                'label' => __('Review Comments', 'real-estate-texas'),
                'name' => 'review_summary_comments',
                'type' => 'textarea',
                'instructions' => __('Customer reviews and comments', 'real-estate-texas'),
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 6,
                'new_lines' => 'wpautop',
            ),
            array(
                'key' => 'field_fbd_email',
                'label' => __('Email', 'real-estate-texas'),
                'name' => 'email',
                'type' => 'text',
                'instructions' => __('Contact email address', 'real-estate-texas'),
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_facebook',
                'label' => __('Facebook', 'real-estate-texas'),
                'name' => 'facebook',
                'type' => 'text',
                'instructions' => __('Facebook profile URL', 'real-estate-texas'),
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_linkedin',
                'label' => __('LinkedIn', 'real-estate-texas'),
                'name' => 'linkedin',
                'type' => 'text',
                'instructions' => __('LinkedIn profile URL', 'real-estate-texas'),
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_twitter',
                'label' => __('Twitter', 'real-estate-texas'),
                'name' => 'twitter',
                'type' => 'text',
                'instructions' => __('Twitter profile URL', 'real-estate-texas'),
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_fbd_youtube',
                'label' => __('YouTube', 'real-estate-texas'),
                'name' => 'youtube',
                'type' => 'text',
                'instructions' => __('YouTube channel URL', 'real-estate-texas'),
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => $customPostKey,
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
}
